#!/bin/sh


#---credentials
AWS_ACCESS_KEY_ID="??"
AWS_SECRET_ACCESS_KEY="??"
AWS_REGION="us-west-2"



AWS_BATCH_JOB_ARRAY_INDEX=0
while [ $AWS_BATCH_JOB_ARRAY_INDEX -le 6 ]
do
    echo $AWS_BATCH_JOB_ARRAY_INDEX
    docker run -e AWS_BATCH_JOB_ARRAY_INDEX="$AWS_BATCH_JOB_ARRAY_INDEX" \
    -e AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
    -e AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
    -e AWS_REGION="$AWS_REGION" \
    jobrunner
    AWS_BATCH_JOB_ARRAY_INDEX=$((AWS_BATCH_JOB_ARRAY_INDEX + 1))

done